# 生产环境配置
spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
  #配置数据源
  datasource:
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为master
      primary: master
      #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      #strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3307/zjt?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
          username: zjt
          password: zjt*_123
          type: com.alibaba.druid.pool.DruidDataSource
        slave_1:
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://xx.xx.xx.xx:3307/xx?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
          type: com.alibaba.druid.pool.DruidDataSource
  redis:
    key:
      prefix:
        userToken: "user:token:"
        passwordError: "user:password:error:"
      expire:
        # 7天 7*24*3600
        userToken: 604800
        # 一个小时
        passwordError: 3600
    # 允许多处登陆
    allowMultipleLogin: false
    host: localhost
    database: 2
    port: 6380
    timeout: 6000
    password: 111111
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 5
#logging配置
logging:
  level:
    com.pqkj: debug
  file: log/${spring.application.name}.log
mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
    banner: true

knife4j:
  production: true #生成环境禁用查看文档